/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;
import br.com.biblisis.controller.CEmprestimo;
import br.com.biblisis.controller.CObra;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author romeu
 */

public class TelaConsultaEmprestimo extends javax.swing.JFrame {

    /**
     * Creates new form TelaConsultaEmprestimo
     */
    private ArrayList <String[]> emprestimos;
    private ArrayList <String[]> emprestimosEncontrados;
    private DefaultListModel modeloLista;
    private String loginAlunoProfessor;
    
    
    
    
    private void constroiListaDeEmprestimos() throws ParseException{
        try {
            this.emprestimos = (ArrayList<String[]>) CEmprestimo.readAll();
         }catch (SQLException e)  {
                System.out.println("Erro!" + e);
        }  
    }
    
    private ArrayList <String[]> buscaEmprestimos (String loginDoUsuario){
        ArrayList <String[]> emprestimosEncontrados = new ArrayList();
        Iterator it = this.emprestimos.iterator();
        String [] emprestimo;
        while (it.hasNext()){
            emprestimo =  (String[]) it.next();
            if (emprestimo[1].equals(loginDoUsuario)){
                emprestimosEncontrados.add(emprestimo);
            }
        }
        return emprestimosEncontrados;
    }

    public void setLoginAlunoProfessor(String loginAlunoProfessor) {
        this.loginAlunoProfessor = loginAlunoProfessor;
    }

    private String [] buscaObra(int codigoDaObra){
        String [] resposta = null;
        try {
            resposta = CObra.search(codigoDaObra);
        }catch (SQLException e) {
            System.out.println("Erro!" + e);
            return resposta;
        }
        return resposta;
    }
    /*
    private int buscaCodigoDoEmprestimo (String [] emprestimoProcurado){
        int indiceProcurado;
        int codigoDoEmprestimo;
        if (this.emprestimos.contains(emprestimoProcurado)){
           indiceProcurado = this.emprestimos.indexOf(emprestimoProcurado);
        }else{
           return -1;   
        } 
        codigoDoEmprestimo = this.emprestimos.size() - indiceProcurado;
        return codigoDoEmprestimo;
    }
    */

    private String geraCodigoDeEmprestimo (String data){
       String [] dataDividida = data.split(" ");
       String hora = dataDividida[1];
       dataDividida = dataDividida[0].split("-");
       String [] horaDividida = hora.split(":");
       String codigoDoEmprestimo = "E" + dataDividida[2] + dataDividida[1] + dataDividida[0] + "-" + horaDividida[0] + horaDividida[1] + horaDividida[2];
       return codigoDoEmprestimo;
    }    
    
    
    public TelaConsultaEmprestimo() {
        initComponents();
        this.modeloLista = new DefaultListModel();
        listaEmprestimos.setModel(modeloLista);
        this.loginAlunoProfessor = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnFechar6 = new javax.swing.JButton();
        lblIdDoUsuario = new javax.swing.JLabel();
        txtLoginId = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaEmprestimos = new javax.swing.JList<>();
        lblFuncionario = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblRegistradoEm = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblObra = new javax.swing.JLabel();
        lblExemplar = new javax.swing.JLabel();
        lblDataDeDevolucao = new javax.swing.JLabel();
        lblObraValor = new javax.swing.JLabel();
        lblDataDeDevolucaoValor = new javax.swing.JLabel();
        lblExemplarValor = new javax.swing.JLabel();
        lblObra1 = new javax.swing.JLabel();
        lblTituloDaObraValor = new javax.swing.JLabel();
        lblDataDeDevolucao1 = new javax.swing.JLabel();
        lblFuncionarioValor = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        lblRegistradoEm1 = new javax.swing.JLabel();
        lblTituloEmprestimo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setText("EMPRÉSTIMO");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnFechar6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8-close-window-24.png"))); // NOI18N
        btnFechar6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFechar6ActionPerformed(evt);
            }
        });

        lblIdDoUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblIdDoUsuario.setText("ID DO USUÁRIO");

        txtLoginId.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtLoginId.setToolTipText("seu ID pode conter letras ou números");
        txtLoginId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtLoginIdMouseClicked(evt);
            }
        });
        txtLoginId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLoginIdKeyReleased(evt);
            }
        });

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        listaEmprestimos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Empréstimos" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaEmprestimos.setToolTipText("clique sobre o empréstimo desejado para mais detalhes");
        listaEmprestimos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaEmprestimosMouseClicked(evt);
            }
        });
        listaEmprestimos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                listaEmprestimosKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(listaEmprestimos);

        lblFuncionario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblFuncionario.setText("Funcionário");
        lblFuncionario.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblRegistradoEm.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblRegistradoEm.setText("Registrado em");
        lblRegistradoEm.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblObra.setText("CÓDIGO DA OBRA");

        lblExemplar.setText("EXEMPLAR");

        lblDataDeDevolucao.setText("DATA DE DEVOLUÇÃO");

        lblObraValor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblObraValor.setText("código da obra");
        lblObraValor.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblDataDeDevolucaoValor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDataDeDevolucaoValor.setText("data de devolução");
        lblDataDeDevolucaoValor.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblExemplarValor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblExemplarValor.setText("código do exemplar");
        lblExemplarValor.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblObra1.setText("TÍTULO DA OBRA");

        lblTituloDaObraValor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTituloDaObraValor.setText("título da ohra");
        lblTituloDaObraValor.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblDataDeDevolucao1.setText("FUNCIONÁRIO RESPONSÁVEL");

        lblFuncionarioValor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblFuncionarioValor.setText("login do funcionário");
        lblFuncionarioValor.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblRegistradoEm1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblRegistradoEm1.setText("Código do Empréstimo");
        lblRegistradoEm1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblTituloEmprestimo.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblTituloEmprestimo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloEmprestimo.setText("CÓDIGO");
        lblTituloEmprestimo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(373, 373, 373)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFechar6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(lblIdDoUsuario)
                                .addGap(18, 18, 18)
                                .addComponent(txtLoginId, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnConsultar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblRegistradoEm)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblRegistradoEm1)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(59, 59, 59)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblObra)
                                                    .addComponent(lblDataDeDevolucao)
                                                    .addComponent(lblDataDeDevolucao1)
                                                    .addComponent(lblObra1))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblFuncionarioValor, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addGap(0, 0, Short.MAX_VALUE)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(lblTituloDaObraValor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(lblObraValor, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(lblExemplarValor, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(lblDataDeDevolucaoValor, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblExemplar)
                                                .addGap(0, 0, Short.MAX_VALUE)))))))
                        .addGap(16, 16, 16)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblTituloEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFechar6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIdDoUsuario)
                            .addComponent(txtLoginId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnConsultar))))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(lblTituloEmprestimo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFuncionario))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRegistradoEm1)))
                    .addComponent(lblRegistradoEm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTituloDaObraValor)
                            .addComponent(lblObra1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblObraValor)
                            .addComponent(lblObra))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblExemplarValor)
                            .addComponent(lblExemplar))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDataDeDevolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDataDeDevolucaoValor))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDataDeDevolucao1)
                            .addComponent(lblFuncionarioValor))))
                .addGap(29, 29, 29))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFechar6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFechar6ActionPerformed
        dispose();
    }//GEN-LAST:event_btnFechar6ActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        listaEmprestimos.setModel(modeloLista);
        modeloLista.clear();
        if (!txtLoginId.getText().isEmpty()){
            emprestimosEncontrados = buscaEmprestimos(txtLoginId.getText()); 
            
            if (!emprestimosEncontrados.isEmpty()){
                Iterator it = emprestimosEncontrados.iterator();
                String [] emprestimo;
                while (it.hasNext()){
                   emprestimo = (String []) it.next();
                   String  codigoDoEmprestimo = geraCodigoDeEmprestimo (emprestimo[4]);
                   String [] dataDividida = emprestimo[4].split(" ");
                   String hora = dataDividida[1];
                   dataDividida = dataDividida[0].split("-");
                   
                   
                   modeloLista.addElement(emprestimo[0] + "        " + dataDividida[2] + "/" + dataDividida[1] + "/" + dataDividida[0] + " às" + hora + "        " + codigoDoEmprestimo );  
                }
            }else{
                JOptionPane.showMessageDialog(null, "O Usuário não possui empréstimos ou não está cadastrado!");  
            }
         }else{
            JOptionPane.showMessageDialog(null, "Preencha o campo do ID!");   
         }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            constroiListaDeEmprestimos();
        } catch (ParseException ex) {
            Logger.getLogger(TelaConsultaEmprestimo.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (this.loginAlunoProfessor != null){
           btnConsultar.setVisible(false);
           txtLoginId.setText(loginAlunoProfessor);
           txtLoginId.setEditable(false);
           listaEmprestimos.setModel(modeloLista);
           modeloLista.clear();
           if (!txtLoginId.getText().isEmpty()){
            emprestimosEncontrados = buscaEmprestimos(txtLoginId.getText());
            if (!emprestimosEncontrados.isEmpty()){
                Iterator it = emprestimosEncontrados.iterator();
                String [] emprestimo;
                
                while (it.hasNext()){
                   emprestimo = (String []) it.next();
                   String  codigoDoEmprestimo = geraCodigoDeEmprestimo (emprestimo[4]);
                   String [] dataDividida = emprestimo[4].split(" ");
                   String hora = dataDividida[1];
                   dataDividida = dataDividida[0].split("-");
                   
                   
                   modeloLista.addElement(emprestimo[0] + "         " + dataDividida[2] + "/" + dataDividida[1] + "/" + dataDividida[0] + " às" + hora + "         " + codigoDoEmprestimo );  
                }
            }else{
                JOptionPane.showMessageDialog(null, "O Usuário não possui empréstimos ou não está cadastrado!");  
            }
         }else{
            JOptionPane.showMessageDialog(null, "Preencha o campo do ID!");   
         }
        }
    }//GEN-LAST:event_formWindowOpened

    private void txtLoginIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLoginIdKeyReleased
         //txtLoginId.setText(txtLoginId.getText().toUpperCase());
    }//GEN-LAST:event_txtLoginIdKeyReleased

    private void listaEmprestimosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaEmprestimosMouseClicked
        if (!modeloLista.isEmpty()){
            String codigoDoEmprestimo;
            int indiceDoElementoSelecionado = listaEmprestimos.getSelectedIndex();
            String[] emprestimoSelecionado = emprestimosEncontrados.get(indiceDoElementoSelecionado);
            String [] obraDoEmprestimo = buscaObra( Integer.parseInt(emprestimoSelecionado[3]));
            codigoDoEmprestimo = geraCodigoDeEmprestimo (emprestimoSelecionado[4]);
            
            if (obraDoEmprestimo != null){
                lblTituloDaObraValor.setText(obraDoEmprestimo[1]);
            }
            lblTituloEmprestimo.setText(codigoDoEmprestimo);
            lblFuncionarioValor.setText(emprestimoSelecionado[0]);
            lblObraValor.setText(emprestimoSelecionado[3]);
            lblExemplarValor.setText(emprestimoSelecionado[2]);
            String [] dataDividida = emprestimoSelecionado[5].split(" ");
            dataDividida = dataDividida[0].split("-");
            lblDataDeDevolucaoValor.setText(dataDividida[2] + "/" + dataDividida[1] + "/" + dataDividida[0]);
        }
    }//GEN-LAST:event_listaEmprestimosMouseClicked

    private void txtLoginIdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLoginIdMouseClicked
        
    }//GEN-LAST:event_txtLoginIdMouseClicked

    private void listaEmprestimosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_listaEmprestimosKeyPressed
         if (!modeloLista.isEmpty()){
            String codigoDoEmprestimo;
            int indiceDoElementoSelecionado = listaEmprestimos.getSelectedIndex();
            String[] emprestimoSelecionado = emprestimosEncontrados.get(indiceDoElementoSelecionado);
            String [] obraDoEmprestimo = buscaObra( Integer.parseInt(emprestimoSelecionado[3]));
            codigoDoEmprestimo = geraCodigoDeEmprestimo (emprestimoSelecionado[4]);
            
            if (obraDoEmprestimo != null){
                lblTituloDaObraValor.setText(obraDoEmprestimo[1]);
            }
            lblTituloEmprestimo.setText(codigoDoEmprestimo);
            lblFuncionarioValor.setText(emprestimoSelecionado[0]);
            lblObraValor.setText(emprestimoSelecionado[3]);
            lblExemplarValor.setText(emprestimoSelecionado[2]);
            String [] dataDividida = emprestimoSelecionado[5].split(" ");
            dataDividida = dataDividida[0].split("-");
            lblDataDeDevolucaoValor.setText(dataDividida[2] + "/" + dataDividida[1] + "/" + dataDividida[0]);
        }
    }//GEN-LAST:event_listaEmprestimosKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaConsultaEmprestimo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnFechar6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblDataDeDevolucao;
    private javax.swing.JLabel lblDataDeDevolucao1;
    private javax.swing.JLabel lblDataDeDevolucaoValor;
    private javax.swing.JLabel lblExemplar;
    private javax.swing.JLabel lblExemplarValor;
    private javax.swing.JLabel lblFuncionario;
    private javax.swing.JLabel lblFuncionarioValor;
    private javax.swing.JLabel lblIdDoUsuario;
    private javax.swing.JLabel lblObra;
    private javax.swing.JLabel lblObra1;
    private javax.swing.JLabel lblObraValor;
    private javax.swing.JLabel lblRegistradoEm;
    private javax.swing.JLabel lblRegistradoEm1;
    private javax.swing.JLabel lblTituloDaObraValor;
    private javax.swing.JLabel lblTituloEmprestimo;
    private javax.swing.JList<String> listaEmprestimos;
    private javax.swing.JTextField txtLoginId;
    // End of variables declaration//GEN-END:variables
}
