/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;
import java.awt.BorderLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author romeu
 */
public class TelaAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form TelaAdministrador
     */
    private String login;
    public TelaAdministrador() {
        initComponents();
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    
    private void novoCadastro (String tipoDoUsuario){
        TelaCadastroUsuario novaTelaDeCadastro = new TelaCadastroUsuario ();
        novaTelaDeCadastro.setTipoDoUsuario(tipoDoUsuario);
        novaTelaDeCadastro.setVisible(true);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuAdministrador = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuItemNovoAdmin = new javax.swing.JMenuItem();
        menuItemNovoUsuario = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MenuItemConsultaAcervo = new javax.swing.JMenuItem();
        menuItemCadastrarNovoItem = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menuItemEncerrarSessao = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Menu do Administrador");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/backgroundPadrao.jpg"))); // NOI18N

        menuAdministrador.setText("Administrador");

        jMenuItem1.setText("Editar dados cadastrais");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuAdministrador.add(jMenuItem1);

        jMenu4.setText("Usuários");

        menuItemNovoAdmin.setText("Cadastrar novo administrador");
        menuItemNovoAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNovoAdminActionPerformed(evt);
            }
        });
        jMenu4.add(menuItemNovoAdmin);

        menuItemNovoUsuario.setText("Cadastrar novo usuário");
        menuItemNovoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNovoUsuarioActionPerformed(evt);
            }
        });
        jMenu4.add(menuItemNovoUsuario);

        jMenuItem9.setText("Editar dados cadastrais de um usuário");
        jMenu4.add(jMenuItem9);

        jMenuItem7.setText("Remover um usuário do sistema");
        jMenu4.add(jMenuItem7);

        menuAdministrador.add(jMenu4);

        jMenuBar1.add(menuAdministrador);

        jMenu2.setText("Acervo");

        MenuItemConsultaAcervo.setText("Consultar acervo");
        MenuItemConsultaAcervo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemConsultaAcervoActionPerformed(evt);
            }
        });
        jMenu2.add(MenuItemConsultaAcervo);

        menuItemCadastrarNovoItem.setText("Cadastrar novo item");
        menuItemCadastrarNovoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadastrarNovoItemActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemCadastrarNovoItem);

        jMenuItem4.setText("Editar item");
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Excluir item");
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Relatório");

        jMenuItem8.setText("Consultar relatório");
        jMenu3.add(jMenuItem8);

        jMenuItem11.setText("Gerar relatório");
        jMenu3.add(jMenuItem11);

        jMenuBar1.add(jMenu3);

        jMenu5.setText("Logout");

        menuItemEncerrarSessao.setText("Encerrar sessão");
        menuItemEncerrarSessao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEncerrarSessaoActionPerformed(evt);
            }
        });
        jMenu5.add(menuItemEncerrarSessao);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1189, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuItemNovoAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNovoAdminActionPerformed
        novoCadastro("Administrador");
    }//GEN-LAST:event_menuItemNovoAdminActionPerformed

    private void menuItemNovoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNovoUsuarioActionPerformed
      Object[] itens = { "Aluno","Funcionário" ,"Professor"};
      Object tipoEscolhido = JOptionPane.showInputDialog(null, "Qual o tipo do usuário?", "Novo usuário",
              JOptionPane.INFORMATION_MESSAGE, null,
                  itens, itens [0]); //
      if (tipoEscolhido != null){
          novoCadastro(tipoEscolhido.toString());
      }
    }//GEN-LAST:event_menuItemNovoUsuarioActionPerformed

    private void MenuItemConsultaAcervoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemConsultaAcervoActionPerformed
        TelaConsultaAcervo novaTelaDeConsulta = new TelaConsultaAcervo();
        novaTelaDeConsulta.setVisible(true);
    }//GEN-LAST:event_MenuItemConsultaAcervoActionPerformed

    private void menuItemCadastrarNovoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadastrarNovoItemActionPerformed
        TelaNovoItem novaTelaDeNovoItem = new TelaNovoItem();
        novaTelaDeNovoItem.setVisible(true);
    }//GEN-LAST:event_menuItemCadastrarNovoItemActionPerformed

    private void menuItemEncerrarSessaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEncerrarSessaoActionPerformed
        int resposta = JOptionPane.showConfirmDialog(null, "Deseja encerrar sua sessão?");
        if (resposta == 0){
           TelaPrincipal novaTela = new TelaPrincipal ();
            novaTela.setVisible(true);
            this.dispose(); 
        }
    }//GEN-LAST:event_menuItemEncerrarSessaoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        menuAdministrador.setText("Olá, " + login+"!");
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new TelaAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuItemConsultaAcervo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenu menuAdministrador;
    private javax.swing.JMenuItem menuItemCadastrarNovoItem;
    private javax.swing.JMenuItem menuItemEncerrarSessao;
    private javax.swing.JMenuItem menuItemNovoAdmin;
    private javax.swing.JMenuItem menuItemNovoUsuario;
    // End of variables declaration//GEN-END:variables
}
